# -*- coding: utf-8 -*-
"""OFDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_LnZPuBfcV8RkhPC7MhTqR-QYSx9t5V
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy as np

# number of bits
N = 100000

# generate random bits
bits = np.random.randint(0, 2, N)

print("Total bits:", len(bits))
print("First 20 bits:", bits[:20])
plt.plot(bits[:100])
plt.title("Random Bits")
plt.show()

# QPSK Modulation

# bits ni pairs ga divide cheyyali
bit_pairs = bits.reshape((len(bits)//2, 2))

symbols = []

for pair in bit_pairs:

    if pair[0] == 0 and pair[1] == 0:
        symbols.append(1+1j)

    elif pair[0] == 0 and pair[1] == 1:
        symbols.append(-1+1j)

    elif pair[0] == 1 and pair[1] == 0:
        symbols.append(1-1j)

    else:
        symbols.append(-1-1j)

symbols = np.array(symbols)

print("First 10 symbols:", symbols[:10])

plt.scatter(symbols.real[:1000], symbols.imag[:1000])
plt.title("QPSK Constellation")
plt.xlabel("Real")
plt.ylabel("Imaginary")
plt.grid()
plt.show()

N_subcarriers = 64
ofdm_symbol = symbols[:N_subcarriers]
ofdm_time = np.fft.ifft(ofdm_symbol)

print("OFDM time signal:", ofdm_time[:10])

plt.plot(ofdm_time.real)
plt.title("OFDM Time Domain Signal")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.grid()
plt.show()

# Rayleigh fading channel

h = (np.random.randn(len(ofdm_time)) + 1j*np.random.randn(len(ofdm_time))) / np.sqrt(2)

print("Channel coefficients:", h[:10])

received_signal = ofdm_time * h
noise = 0.1*(np.random.randn(len(received_signal)) + 1j*np.random.randn(len(received_signal)))

received_signal = received_signal + noise
received_fft = np.fft.fft(received_signal)
equalized_symbols = received_fft / h

plt.scatter(equalized_symbols.real[:100], equalized_symbols.imag[:100])
plt.title("Received QPSK Constellation")
plt.xlabel("Real")
plt.ylabel("Imaginary")
plt.grid()
plt.show()

received_bits = []

for sym in equalized_symbols:

    if sym.real > 0 and sym.imag > 0:
        received_bits.extend([0,0])

    elif sym.real < 0 and sym.imag > 0:
        received_bits.extend([0,1])

    elif sym.real > 0 and sym.imag < 0:
        received_bits.extend([1,0])

    else:
        received_bits.extend([1,1])

received_bits = np.array(received_bits)

print("First received bits:", received_bits[:20])

snr_db_range = [0,5,10,15,20]
ber_values = []

for snr_db in snr_db_range:

    snr_linear = 10**(snr_db/10)

    signal_power = np.mean(np.abs(received_signal)**2)

    noise_power = signal_power / snr_linear

    noise = np.sqrt(noise_power/2) * (np.random.randn(len(received_signal)) + 1j*np.random.randn(len(received_signal)))

    received_signal_noisy = received_signal + noise

    received_fft = np.fft.fft(received_signal_noisy)

    equalized_symbols = received_fft / h

    received_bits = []

    for sym in equalized_symbols:

        if sym.real > 0 and sym.imag > 0:
            received_bits.extend([0,0])

        elif sym.real < 0 and sym.imag > 0:
            received_bits.extend([0,1])

        elif sym.real > 0 and sym.imag < 0:
            received_bits.extend([1,0])

        else:
            received_bits.extend([1,1])

    received_bits = np.array(received_bits)

    original_bits = bits[:len(received_bits)]

    errors = np.sum(original_bits != received_bits)

    BER = errors / len(original_bits)

    ber_values.append(BER)

plt.plot(snr_db_range, ber_values, marker='o')
plt.title("BER vs SNR for OFDM")
plt.xlabel("SNR (dB)")
plt.ylabel("BER")
plt.grid()
plt.show()

plt.scatter(equalized_symbols.real, equalized_symbols.imag)
plt.title("Received QPSK Constellation")
plt.xlabel("Real")
plt.ylabel("Imaginary")
plt.grid()
plt.show()

N_subcarriers = 64

pilot_positions = np.arange(0, N_subcarriers, 8)

pilot_value = 1+1j

ofdm_symbol = np.zeros(N_subcarriers, dtype=complex)

data_index = 0

for i in range(N_subcarriers):

    if i in pilot_positions:
        ofdm_symbol[i] = pilot_value
    else:
        ofdm_symbol[i] = symbols[data_index]
        data_index += 1
received_fft = np.fft.fft(received_signal)
h_est = np.interp(np.arange(N_subcarriers),
                  pilot_positions,
h_est[pilot_positions])
equalized_symbols = received_fft / h_est
plt.scatter(equalized_symbols.real, equalized_symbols.imag)
plt.title("Equalized Constellation")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# System Parameters
# -----------------------------
N_bits = 100000
N_subcarriers = 64
cp_len = 16

snr_db_range = np.arange(0,21,5)

pilot_positions = np.arange(0,N_subcarriers,8)
pilot_value = 1+1j

ber_values = []

# -----------------------------
# Random Bits
# -----------------------------
bits = np.random.randint(0,2,N_bits)

if len(bits)%2 != 0:
    bits = np.append(bits,0)

# -----------------------------
# QPSK Modulation
# -----------------------------
bit_pairs = bits.reshape((len(bits)//2,2))

symbols = []

for pair in bit_pairs:

    if pair[0]==0 and pair[1]==0:
        symbols.append(1+1j)

    elif pair[0]==0 and pair[1]==1:
        symbols.append(-1+1j)

    elif pair[0]==1 and pair[1]==0:
        symbols.append(1-1j)

    else:
        symbols.append(-1-1j)

symbols = np.array(symbols)

# -----------------------------
# SNR Simulation Loop
# -----------------------------
for snr_db in snr_db_range:

    # Create OFDM symbol
    ofdm_symbol = np.zeros(N_subcarriers, dtype=complex)

    data_index = 0

    for i in range(N_subcarriers):

        if i in pilot_positions:
            ofdm_symbol[i] = pilot_value

        else:
            ofdm_symbol[i] = symbols[data_index]
            data_index += 1

    # OFDM Modulation
    ofdm_time = np.fft.ifft(ofdm_symbol)

    # Add Cyclic Prefix
    cp = ofdm_time[-cp_len:]
    ofdm_tx = np.concatenate([cp,ofdm_time])

    # Rayleigh Channel
    h = (np.random.randn(len(ofdm_tx)) + 1j*np.random.randn(len(ofdm_tx))) / np.sqrt(2)

    signal_channel = ofdm_tx * h

    # AWGN Noise
    signal_power = np.mean(np.abs(signal_channel)**2)

    snr_linear = 10**(snr_db/10)

    noise_power = signal_power/snr_linear

    noise = np.sqrt(noise_power/2)*(np.random.randn(len(signal_channel)) +
                                    1j*np.random.randn(len(signal_channel)))

    received_signal = signal_channel + noise

    # Remove Cyclic Prefix
    received_no_cp = received_signal[cp_len:]

    # FFT Demodulation
    received_fft = np.fft.fft(received_no_cp)

    # -----------------------------
    # Pilot-based Channel Estimation
    # -----------------------------
    h_est = np.zeros(N_subcarriers, dtype=complex)

    for p in pilot_positions:
        h_est[p] = received_fft[p] / pilot_value

    # Interpolation
    h_est_real = np.interp(np.arange(N_subcarriers),
                           pilot_positions,
                           h_est[pilot_positions].real)

    h_est_imag = np.interp(np.arange(N_subcarriers),
                           pilot_positions,
                           h_est[pilot_positions].imag)

    h_est = h_est_real + 1j*h_est_imag

    # Equalization
    equalized_symbols = received_fft / h_est

    # -----------------------------
    # QPSK Demodulation
    # -----------------------------
    received_bits = []

    for sym in equalized_symbols:

        if sym.real > 0 and sym.imag > 0:
            received_bits.extend([0,0])

        elif sym.real < 0 and sym.imag > 0:
            received_bits.extend([0,1])

        elif sym.real > 0 and sym.imag < 0:
            received_bits.extend([1,0])

        else:
            received_bits.extend([1,1])

    received_bits = np.array(received_bits)

    original_bits = bits[:len(received_bits)]

    errors = np.sum(original_bits != received_bits)

    ber = errors/len(original_bits)

    ber_values.append(ber)

# -----------------------------
# BER vs SNR Plot
# -----------------------------
plt.figure()

plt.plot(snr_db_range, ber_values, marker='o')

plt.xlabel("SNR (dB)")
plt.ylabel("BER")
plt.title("BER vs SNR for OFDM System")

plt.grid()

plt.show()

# -----------------------------
# Constellation Plot
# -----------------------------
plt.figure()

plt.scatter(equalized_symbols.real, equalized_symbols.imag)

plt.xlabel("Real")
plt.ylabel("Imaginary")

plt.title("Received QPSK Constellation")

plt.grid()

plt.show()